// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umkrjqrrbobgcwisddzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVta3JqcXJyYm9iZ2N3aXNkZHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2MzI2NTAsImV4cCI6MjA4ODIwODY1MH0.yw5-RH5wfvXJaxvds27dfUPMASHcSJofsgi7JmFsS4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
